# action.yml
name: 'Docker Run Action'
description: 'Run a command in a new container'
inputs:
  options:
    description: 'Options'
    required: true
  pr:
    description: 'pr url'
    required: true
  command:
    description: 'Use a specific command'
    required: true
    default: review
  username:
    description: 'Username'
    required: false
  password:
    description: 'Password'
    required: false
  github:
    description: 'Github payload'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
